name: project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0-165.0.dev

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.11
  flutter_animate: ^4.5.2
  flutter_libserialport: ^0.6.0
  google_fonts: ^6.3.2
  provider: ^6.1.5+1
  usb_serial: ^0.5.2
  serial: ^0.0.7+1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
